name: Publish Linux

on:
  workflow_dispatch:

jobs:
  publish:
    if: ${{ github.repository == 'ericcayers-ai/midi-jar' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Install libasound2-dev
        run: sudo apt-get install -y libasound2-dev

      - name: Install Flatpak dependencies
        run: |
          sudo apt-get install -y flatpak flatpak-builder elfutils
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: npm
          registry-url: 'https://npm.pkg.github.com'
          scope: '@la-jarre-a-son'

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          npm install

      - name: Publish releases
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run postinstall
          npm run build
          npm exec electron-builder -- --publish always --linux
